export type SignupModel = {
  userId: string | undefined;
  userPw: string | undefined;
  userName: string | undefined;
  residentNumber: string | undefined;
  gender: string | undefined;
  engName: string | undefined;
  task: string | undefined | undefined;
  empNo: string | undefined;
  hiredate: Date | string | undefined;
  family: string | undefined;
  armyStart: Date | string | undefined;
  armyEnd: Date | string | undefined;
  armyBranch: string | undefined;
  birthday: Date | string | undefined;
  tel: string | undefined;
  emergencyTel: string | undefined;
  userEmail: string | undefined;
  address: string | undefined;
  techGrade: string | undefined;
  position: string | undefined;
  spot: string | undefined;
  loc: string | undefined;
  locDetail: string | undefined;
  scienceTechCertify: string | undefined;
  admincheck: number | undefined;
  highschool: string | undefined;
  education: string | undefined;
  gradSchool: string | undefined;
};
